### ISSUE TITLE
Feature Request: Multiselect

### ISSUE THREAD

**Issue by mborders** [rafaelpimpa/buefy#121]
I know that Bulma doesn't have a multiselect input, but what are your thoughts on adding one?

**Comment by rafaelpimpa** [comment]
I want to implement the tag/chips input like this one: http://aehlke.github.io/tag-it/

It could work with random text or within an array of options.

**Comment by mborders** [comment]
Ah yes, I believe that would work well. Thanks!

**Comment by jivemonkey2000** [comment]
Would also love to see this also. Had a requirement for this recently and threw something together using the autocomplete component and native Bulma tags, which was functional, but didn't have the time to develop it further as I would have liked to..

![screen shot 2017-06-30 at 11 21 11](https://user-images.githubusercontent.com/17082749/27731777-5b76c9d8-5d86-11e7-8fb8-0dc483e975af.png)

**Comment by rafaelpimpa** [comment]
That's basically what I'm gonna do TBH :D

**Comment by jgerbes** [comment]
I have been working on a component to do this. Would be happy to submit a pull request, but feel that it would be better to wait until Bulma@0.5.0 is supported, as tags have been changed.

**Comment by rafaelpimpa** [comment]
@jgerbes Hey thanks but I've just started it!

**Comment by rafaelpimpa** [comment]
Actually, @jgerbes, you can submit your PR if you want, maybe we can work together.

**Comment by jgerbes** [comment]
@rafaelpimpa Happy to submit a PR, will just need to update to Bulma 5.0 and tidy up. 

So that we are aligned, here are my thoughts/intentions:

 **Name**
I was going to go with tags-input, which I guess it would be `b-tags-input` as part of Buefy. Happy for suggestions if you can think of something more suitable.

**Completed features**
I have started off simple with a component that would initially:

- Support `v-model`.
- Prop to change placeholder "Add a tag" text.
- Show list of tags as Bulma tags with delete buttons.
- Include integrated input field for tag input (like [tag-it](http://aehlke.github.io/tag-it/)).
- Focus state handling.
- Ignore duplicate tags (though I feel this could be handled more nicely).
- Add tag by pressing enter or comma (",").
- Add tag when focus lost.
- Remove specific tag by clicking its delete button.
- Remove last tag by pressing backspace when input empty - the tags value is added to input so that you can change it/backspace it completely (though maybe it would be better if pressing delete selects last tag and pressing it again deletes it - thoughts?).
- Maxlength tags limit + help counter.

**Unimplemented features**
These are some features that could be added that I currently haven't built:

- Autocomplete (would love input on the best strategy for this).
- Readonly (though I'm not sure if this is necessary, thoughts?).
- Emit events on add/remove (easy enough but haven't gotten around to it yet as I just use v-model).
- Transitions/animations for add, remove and invalid input.
- Icons (like icons in normal input).
- Tag class (for colours).

**Other thoughts**

- This component could be incorporated into the `b-input` component (`type="tags"`), but some changes would need to be made.

**Comment by rafaelpimpa** [comment]
Sorry for the delay @jgerbes!

We are aligned in most of the specs, the main hesitation I have is about using the ``b-autocomplete`` or the ``b-select`` for this, I think the autocomplete is better for desktop but for mobile the select is better.

> Remove last tag by pressing backspace when input empty - the tags value is added to input so that you can change it/backspace it completely (though maybe it would be better if pressing delete selects last tag and pressing it again deletes it - thoughts?).

Not sure about this, maybe make tags with tabindex and let user use tab or shift+tab between tags is the better way.

I'll add some other thoughts later on.

**Comment by jgerbes** [comment]
Hey @rafaelpimpa.

Thanks for sharing your initial thoughts. I am currently integrating this into Buefy and will submit a pull request later today. It's a very early version and will need refinement.

I am opposed to using tab and shift+tab to move between tags because its never a good idea (for accessibility purposes) to change the tab order/behaviour of a form.

Also, moving between the tags (with tab or arrow keys) isn't going to be possible on mobile, so I felt it was better just to leave it out.

**Comment by jgerbes** [comment]
Please see #244

**Comment by sufian07** [comment]
When will the feature be available?

**Comment by jgerbes** [comment]
@sufian07 an implementation has been started - see #244. I'm currently waiting for @rafaelpimpa's input before going further.

**Comment by rafaelpimpa** [comment]
Added tag input in dev branch
