### ISSUE TITLE
Autocomplete with select

### ISSUE THREAD

**Issue by LusenkoSasha** [rafaelpimpa/buefy#222]
![image](https://user-images.githubusercontent.com/27783985/28960064-d5bee1d6-7905-11e7-896d-24d55f1c76f0.png)

**Comment by jtommy** [comment]
@LusenkoSasha It's just like @Tirke said about autocomplete component

**Comment by JoshZA** [comment]
👍 for this feature

**Comment by ivalkenburg** [comment]
Would love select with autocomplete features as well

**Comment by dumptyd** [comment]
@Tirke Could you please make a fiddle or just tell me how you'd simulate select+search with `b-autocomplete`?

**Comment by Tirke** [comment]
@dumptyd 

I'm sorry I don't have a lot of time to provide a fiddle, but basically you juste use `v-model` to simulate the select and you use existing search features of the autocomplete component to achieve search.

This is not at all a fully featured select but you'll have something working. If you want something more I highly suggest looking at `vue-multiselect` or other projects.

**Comment by johnpyp** [comment]
The only other feature I would want for the current autocomplete is the ability to have the results show when the person hasn't typed anything. Show all the data just sorted alphabetically.

**Comment by jtommy** [comment]
@johnpyp We are working on it!

**Comment by johnpyp** [comment]
Good to hear! Not a super big deal, but it would be a great feature :)

**Comment by gfviegas** [comment]
@Tirke of course there's components that has this feature around the web, but we are using buefy for a reason, right? 

Buefy components have the look and feel that we seek in bulma and we follow all the patterns of buefy components (same attributes, the b-field "integration", etc...).

It sucks using vue-multiselect with buefy forms.. it breaks the form since its a different stylesheet, the responsiveness ain't that great and there's not the state classes, icons, etc....

And I think the current b-select might as well just be improved to support this functionality

**Comment by Tirke** [comment]
@gfviegas 

Yeah, of course in an ideal world `b-select` should provide this functionality. But when you have deadlines and you need to ship a product you don't always have the choice of waiting on Buefy dev team. And Buefy dev team is not the most active and I don't think that it's the most healthy open source project. Just look at [element](https://github.com/ElemeFE/element) or [vuetify](https://github.com/vuetifyjs/vuetify) if you want to see what I consider an healthy open source project.
I'm not saying that to discredit Buefy, I think that Buefy is really great, but I also think that it will take time (maybe a lot) before we see a solid multi `b-select`.

Providing a good multiselect component is hard, and time consuming. Just look at `vue-multiselect` history. I'm just trying to provide a solution here, and I repeat myself but waiting is not always one.

And about using `vue-multiselect` with buefy forms, what you are saying is just not true. We shipped a product in September with Buefy + `vue-multiselect` used in many forms and it took me ~1 hour to have something looking exactly like Buefy `b-select`.

**Comment by rafaelpimpa** [comment]
You can now use autocomplete with ``open-on-focus`` prop to work like a custom select (and it now has scrollbars).

**Comment by dumptyd** [comment]
Awesome! Thanks.

**Comment by aantn** [comment]
I would also like this.

@rafaelpimpa that is a good solution but it doesn't work for multiselect.

**Comment by jtommy** [comment]
@aantn there is tagsinput

**Comment by aantn** [comment]
Hi @jtommy , thank you for the fast response.

I've tried using tagsinput but it isn't appropriate for my use case. The user can choose many tags and displaying all the chosen tags takes up too much space on the screen. A UI like multi-select works better because the chosen tags are shown only when opening the multi-select.

I would be happy to open a PR for this myself, but I would like some direction on how to handle it. Should this be an extension of multi-select? Should it be part of dropdown? Should it be part of autocomplete?

**Comment by jtommy** [comment]
Can you make an example?

**Comment by aantn** [comment]
![image](https://user-images.githubusercontent.com/494087/130755135-472be5b8-2a46-4b8b-a3bc-4e5fed60f07e.png)

**Comment by aantn** [comment]
What I'm trying to create here is three smallish filters aligned on the right side of the page.

![image](https://user-images.githubusercontent.com/494087/130755397-a660434e-e18c-40e4-820d-879eba78aba3.png)

**Comment by jtommy** [comment]
Ok, but what's the problem with tag, I need an example of UI/UX

**Comment by aantn** [comment]
Just to clarify, that dropdown is only shown when the users clicks on the filter menu.

**Comment by jtommy** [comment]
Ok, then the dropdown multiple is the best option for you
