### ISSUE TITLE
Request: Sticky table headers

### ISSUE THREAD

**Issue by jamespdaily** [rafaelpimpa/buefy#227]
Not sure if this one is possible but it would be nice to have an option to make table headers "sticky" so that when you scroll down the page the column headers are still visible.

**Comment by rafaelpimpa** [comment]
I don't think this is ever going to be implemented. Because:

- To work with ``position: sitcky`` we would have to change all table ``display`` types since it doesn't work with any ``table-*``, it's a no-no.
- Or hardcode it on JavaScript which I don't really like, event listeners on scrolls are always laggy.

**Comment by jtommy** [comment]
Added a54e146840a0f4d5eb323317f907f97a5d78f88d
