### ISSUE TITLE
Datepicker selection sets day before selected date (timezone issue?)

### ISSUE THREAD

**Issue by Kaeltis** [rafaelpimpa/buefy#362]
### Overview of the problem

**Buefy** version: 0.5.3
**Vuejs** version: 2.4.4
**OS/Browser**: Linux/Chrome 61.0.3163.100

### Description

I still have this issue from #275, when creating a Datepicker and setting it to new Date() its working, but when selecting a date, it's setting the Date to the day before at 22:00.

### Steps to reproduce

```
<template>
    <div class="card-content">
        <b-field label="Date">
            <b-datepicker
                    placeholder="Select Date"
                    v-model="modelData.assignment_date"
                    icon="calendar"
                    :first-day-of-week="1"
                    :month-names="monthNames"
                    :day-names="dayNames">
            </b-datepicker>
        </b-field>

        {{ modelData.assignment_date }}
    </div>
</template>

<script>
    export default {
        data() {
            return {
                monthNames: ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
                dayNames: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
                modelData: {
                    assignment_date: new Date(),
                }
            }
        }
    }
</script>
```
After reloading, modelData.assignment_date is correctly set to Today
![screenshot_20171007_164541](https://user-images.githubusercontent.com/809734/31308944-0c0244b2-ab7f-11e7-9baf-b323e9e47558.png)

After picking a Day (10/6/2017), modelData.assignment_date is set to the day before the one I selected at 22:00
![screenshot_20171007_164557](https://user-images.githubusercontent.com/809734/31308949-2027df88-ab7f-11e7-948c-b14b91edc173.png)

### Expected behavior

When picking 10/6/2017 as Day, set modelData.assignment_date to "2017-10-06T00:00:00.000Z"

### Actual behavior

When picking 10/6/2017 as Day, it sets modelData.assignment_date to "2017-10-05T22:00:00.000Z"

**Comment by Kaeltis** [comment]
This seems like a Timezone issue, we are in UTC+2 and the date picker seems to convert that to UTC

**Comment by jtommy** [comment]
@Kaeltis It's only a problem about your formatting code.
For example try ` {{ modelData.assignment_date.toString() }}` and i think you'll see correct date.

**Comment by Kaeltis** [comment]
Thanks for the hint, I'm now passing the date through moment.js and outputting it as YYYY-MM-DD and I'm getting the correct date that way.

**Comment by aalabiso** [comment]
I'm experiencing this issue as well. The problem is that the Javascript Date Object is formatted to browser's local timezone. So if you create a Date object from a record in your database that's in UTC time, it will be represented as the equivalent date in your locale. 

 For instance if you are in UTC+8 and select the date 2018-08-01, the Date object looks like "Wed Aug 01 2018 00:00:00 GMT+0800". However when the form is submitted the value up being "2018-07-31T16:00:00.000Z" which is the same date, converted into UTC format. 

  Sure, you can do a bunch of translation in Vue or intercepts via axios to get it to "work right" but the intent of the input is to select a date (absent a time or timezone). The date picker doesn't implement times or timezones so this can get a bit confusing. The Javascript Date object represents a date, a time and a timezone but the Date Picker should only represent a date. For most use cases developers need a method to view/store/modify a date without an associated time/timezone so it might make more sense for Buefy to drop the Date object in favor of a date string.
