### ISSUE TITLE
Feature Request - Allow autocomplete with new tags for b-taginput

### ISSUE THREAD

**Issue by gkinsman** [rafaelpimpa/buefy#482]
### Overview of the problem

It's not possible at the moment to use b-taginput to both autocomplete, and suggest new items. Adding the autocomplete modifier prevents the handling of tags that don't exist in the tag list.

**Buefy** version: 0.6.2
**Vuejs** version: 2.5.2
**OS/Browser**: Chrome

### Expected behavior

It'd be great if there was a modifier like allow-new that was orthogonal to autocomplete that allowed new suggestions.

### Actual behavior

Adding autocomplete prevents new tags from being added.

**Comment by pdiveris** [comment]
Hi there,

I am not sure if that's of any help but faced with this problem I solved it as follows.

1. My taginput declaration:

```   
             <b-taginput
                    v-model="tags"
                    :data="filteredTags"
                    autocomplete
                    field="tag"
                    icon="label"
                    placeholder="Add a tag"
                    @typing="getFilteredTags"
                    @keydown.native="myKeydown($event, $event.target.value)"
                >
```
2. My data (filterTags gets populated on mounted() via an async call

```
        data() {
                return {
                    filteredTags: [],
                    data: [],
                    editor: null,
                    tags: [],
                    tag: ""
                }
            },

```
4. getFilteredTags. This re-loads the suggestions from the API but removes any tags already selected. The `text` parameter is added as I am investigating whether it's worth only fetching those matching the text, I haven't made my mind up. Also, one could exclude the already selected tags straight through the API. I have spent many days getting this to work due to the weirdness mentioned in (5) so haven't had the chance to optimise!

```
                getFilteredTags(text) {
                    axios.get(`/api/tags/`, config)
                        .then(response => {

                            // JSON responses are automatically parsed.
                            let d = response.data.data;

                            this.filteredTags = _.differenceWith(d, this.tags, _.isEqual);
                            this.loading = false;

                        })
                        .catch(e => {
                            //  this.errors.push(e)
                            console.log(e);
                        });
                },

```
5. Finally, the call on keydown. Now, the idea is that before pushing into the tags array one would want to add to the tags "table" or collection via the API, and have the new key returned to use (instead of the AAAAAAA one shown here,) but that's standard stuff. What bugged me for days is that without the call to `this.tags.pop();` one would get back two tags, the one at the top of the "old" list, and the newly added one! If anyone has any ideas why that might be so, please let me know! 

```
                myKeydown(event, newTag) {

                    if (event.keyCode === 13 || event.keyCode === 188) {
                        console.log(`Key was pressed ${event.keyCode}`);
                        console.log(`newTag was ${newTag}`);

                        event.preventDefault();

                        this.tags.pop();
                        
                        this.tags.push({"_key": "AAAAAAA", "tag": newTag});

                    }

                },
```
