### ISSUE TITLE
Searchable Table

### ISSUE THREAD

**Issue by fsfj** [rafaelpimpa/buefy#555]
Hello, How to add search box in table? Is it possible?

Thank you.

**Comment by avrong** [comment]
You can add v-input outside of table and filter table rows by computed variable

**Comment by jtommy** [comment]
@fsfj  Agree with @avrong

**Comment by fsfj** [comment]
Okay, thank you guys!

**Comment by feelslike1929** [comment]
@avrong @jtommy could you provide an example or more description on how this would be done? I'm fairly new to vuejs & buefy so I would appreciate any extra info, thanks!

**Comment by avrong** [comment]
@feelslike1929 [done](https://codepen.io/avrong/pen/KoQZor)

**Comment by fsfj** [comment]
thanks @avrong

**Comment by yxxa** [comment]
helped me, thx
+1 @avrong

**Comment by tonystonee** [comment]
I decided to fork this repo and make my own solution. This is what I came up with:

![search](https://user-images.githubusercontent.com/9577765/48146224-7c124c80-e282-11e8-8b6f-c622b7e5cf15.gif)

Repo:
[https://github.com/tonystonee/buefy/tree/SearchFilter](https://github.com/tonystonee/buefy/tree/SearchFilter)
I haven't made a PR yet because I haven't made a mobile solution for this feature. (It wasn't needed in my project).

If anyone wants to help out with the mobile side, feel free!

**Comment by amirhkhadem** [comment]
@avrong I used this method but it seems a bit slow for my table. My table is loading Json through a php file into the buefy table in Vue. Any suggestions to make it faster?

**Comment by viralpatel380** [comment]
> @feelslike1929 [done](https://codepen.io/avrong/pen/KoQZor)

Data Getting Duplicate
